#!/usr/bin/env bash

comptonDir=$HOME/.config/awesome/configuration/compton.conf

case $1 in
	'enable')
  eval "kill -9 $(pidof compton)"
  eval "sed -i -e 's/blur-background-frame = false/blur-background-frame = true/g' "${comptonDir}""
  eval "compton --config ${comptonDir} &"
  notify-send 'System Notification' 'Blur effects are now enabled!'
	;;
	'disable')
  eval "kill -9 $(pidof compton)"
  eval "sed -i -e 's/blur-background-frame = true/blur-background-frame = false/g' "${comptonDir}""
  eval "compton --config ${comptonDir} &"
  notify-send 'System Notification' 'Blur effects are now disabled!'
	;;
esac
