#!/bin/bash
# Description: Display cover for the current playing song using notify-send

# source colors
. $HOME/.local/bin/color-parser


#variables
MUSIC_DIR=/home/gerome/Music/
COVER=/tmp/cover2.jpg


# create notify title
#title="<span foreground='$MAGENTA'>Now Playing</span>"
title="Now Playing"


function reset_background
{
    printf "\e]20;;100x100+0+0\a"

}

{
    album="$(mpc --format %album% current)"
    file="$(mpc --format %file% current)"
    album_dir="${file%/*}"
    [[ -z "$album_dir" ]] && exit 1
    album_dir="$MUSIC_DIR"

    covers="$(find "$album_dir" -type d -exec find {} -maxdepth 1 -type f -iregex ".*/.*\(${album}\|cover\|folder\|artwork\|front\).*[.]\(jpe?g\|png\|gif\|bmp\)" \; )"
    src="$(echo -n "$covers" | head -n1)"
    rm -f "$COVER"
    if [[ -n "$src" ]] ; then
        #resize the image's height to 300px & extent it to cover the urxvt length
        convert "$src" -resize 100x "$COVER"

        if [[ -f "$COVER" ]] ; then

           #-- original script --
           #scale down the cover to 30% of the original
           #place it 1% away from left and 50% away from top.
           #printf "\e]20;${COVER};70x70+0+4:op=keep-aspect\a"
           #---------------------

           #no need to scale down, i have extent it



           dunstify -r 12 -i $COVER "$title" "$(mpc current)"

        else
            reset_background
        fi
    else
        reset_background
    fi
} &
