#!/bin/sh
# A simple Todo List using notify-send
unset image
mpd_artist=$(mpc -p 6600 -f "%artist%" | head -1)
mpd_title=$(mpc -p 6600 -f "%title%" | head -1)
mpd_album=$(mpc -p 6600 -f "%album%" | head -1)
/home/gerome/.ncmpcpp/extract_cover.sh
image="/tmp/mpd-track-cover.jpg"


notify-send -i "$image" "Artist : $mpd_artist
Song   : $mpd_title
Album  : $mpd_album"
