#!/usr/bin/env bash


# Source generated colors.
source "${HOME}/.local/bin/color-parser"

reload_dunst() {
    pkill dunst
    dunst \
        -lb "$BG" \
        -nb "$BG" \
        -cb "$RED" \
        -lf "$FG" \
   #     -bf "$color15" \
        -cf "$FG" \
        -nfr "$FG" \
        -nf "$FG"
}

generate_zathurarc(){
   . $HOME/.local/bin/gen-zathurarc > $HOME/.config/zathura/zathurarc
}

main() {
    reload_dunst &
    generate_zathurarc 
}

main
