#!/usr/bin/env bash


dir=$HOME/Pictures/Screenshots

if [[ ! -d $dir ]]; then
	mkdir -p $dir
fi


case $1 in
	'full')
	eval "maim -u -m 1 $dir/$(date +%Y%m%d_%H%M%S).png"
	eval "xclip -selection clipboard -t image/png -i $dir/`ls -1 -t $dir | head -1` &"
	#PIDMIX=$!
	notify-send 'System Notification' 'Full Screenshot saved and copied to clipboard!'
	#wait $PIDIOS
	#wait $PIDMIX
	;;
	'area')
	eval "maim -u -s -m 1 $dir/$(date +%Y%m%d_%H%M%S).png"
	eval "xclip -selection clipboard -t image/png -i $dir/`ls -1 -t $dir | head -1` &"
	#PIDMIX=$!
	notify-send 'System Notification' 'Area Screenshot saved and copied to clipboard!'
	#wait $PIDIOS
	#wait $PIDMIX
	;;
esac
